Algoritmo "MOD E DIV"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 5/17/2024
Var
// Seção de Declarações das variáveis 
           w, x, y, z : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

      x <- 10
      y <- 3
      z <- x DIV y     //Operador DIV retorna a parte inteira da divisao
      w <- x % y       // Operador % (modulo) resto da divisao
      escreval(z)
      escreval(w)
Fimalgoritmo