Algoritmo "mod e Div2"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 5/17/2024
Var
// Seção de Declarações das variáveis 

   x: inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
             escreval("Digite um numero:")
             leia(x)
             
             se x % 2 == 0 entao
                escreval("Numero Par")
             senao
                  escreva("Numero Impar)

Fimalgoritmo