Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Jonathan Costa
// Data atual  : 5/17/2024
Var
// Seção de Declarações das variáveis 
      palavra1, palavra2, palavra3: caractere
      numero1, numero2, soma: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
   escreval("Digite uma palavra")
   leia(palavra1)
   
   escreval("Digite outra palavra")
   leia(palavra2)
   
   palavra3 <- palavra1 + palavra2
   
   escreval("Digite um numero")
   leia(numero1)
   
   escreval("Digite outro numero")
   leia(numero2)
   
   soma <- numero1 + numero2
   
   escreval(palavra1 + " " + palavra2)
   escreval(soma)
   

Fimalgoritmo