Algoritmo "Trabalhando com Tipos"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 6/1/2024
Var
// Seção de Declarações das variáveis 
        palavra1, palavra2, palavra3: caractere
        numero1, numero2, numero3: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
        escreval("Digite palavra 1")
        leia(palavra1)
        
        escreval("Digite palavra 2")
        leia(palavra2)
        
        palavra3 <- palavra1 + palavra2


        escreval("Digite numero 1")
        leia(numero1)

        escreval("Digite numero 2")
        leia(numero2)

        numero3 <- numero1 + numero2
        
        escreval(palavra3)
        escreval(numero3)
        
Fimalgoritmo